# Site settings
title: Chicago Real Estate Video Blog
email: bryce@getvyral.com
description: > # this means to ignore newlines until "baseurl:"
  A Blog for the real estates
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site


#Handling Reading
encoding: "utf-8"
markdown_ext: "markdown, md"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems:
  - jemoji
  - octopress-autoprefixer
# Excludes
exclude:
  - node_modules
  - bower_components
  - .sass-cache

sass:
  sass_dir: _sass
  style: :nested
