# Site settings
title: Vyral-Jekyll
email: bryce@getvyral.com
description: > # this means to ignore newlines until "baseurl:"
  A Blog for the real estates
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brycestradling.com" # the base hostname & protocol for your site
twitter_username: losslessdesign
github_username:  Cutcopy

#Handling Reading
encoding: "utf-8"
markdown_ext: "markdown, md"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems:
  - jemoji
  - octopress-autoprefixer
# Excludes
exclude:
  - node_modules
  - bower_components
  - .sass-cache

sass:
  sass_dir: _sass
  style: :nested

# Navigation
navigation:
 - title: Home
   url: /index.html
 - title: Projects
   url: /projects.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html
