# Site settings
title: Chicago Real Estate Video Blog
email: bryce@getvyral.com
image: /img/vyral-icon.png
lang: en
fb-admins: 63206588
description: A Blog for the real estates.
keywords: Junk, Culture, spit, steel
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site

#Handling Reading
encoding: "utf-8"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

paginate: 5

gems:
  - jemoji
  - octopress-autoprefixer
  - jekyll-paginate
# Excludes
exclude:
  - node_modules
  - bower_components
  - .sass-cache

sass:
  sass_dir: _sass
  style: :nested
