# Site settings
title: San Francisco Real Estate Video Blog
email: someone@email.com
author: Durwin Cheung
image: /img/vyral-icon.png
lang: en
fb-admins: 63206588
description: A Blog for the real estates.
keywords: Junk, Culture, spit, steel
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://giant-pepper.cloudvent.net" # the base hostname & protocol for your site

#fonts
body_font:
    - helvetica, sans-serif
    - georgia, serif
    - courier, mono
    - fantasy
#fonts
header_font:
    - helvetica, sans-serif
    - georgia, serif
    - courier, mono
    - fantasy

#Handling Reading
encoding: "utf-8"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

paginate: 5

gems:
  - jemoji
  - octopress-autoprefixer
  - jekyll-paginate
  - jekyll-sitemap
# Excludes
exclude:
  - node_modules
  - bower_components
  - .sass-cache

sass:
  sass_dir: _sass
  style: :nested
