# Site settings
title: Chicago Real Estate Video Blog
email: bryce@getvyral.com
description: > # this means to ignore newlines until "baseurl:"
  A Blog for the real estates
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site


#Handling Reading
encoding: "utf-8"
markdown_ext: "markdown, md"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems:
  - jemoji
  - octopress-autoprefixer
# Excludes
exclude:
  - node_modules
  - bower_components
  - .sass-cache

sass:
  sass_dir: _sass
  style: :nested

#Client Shit
client:
  name: Joe Somebody
  company: Castle Greyskull
  address: 123 Fake St. Eternia, NE
  phone: 1-234-567-8910
  email: Someone@email.com
  url: getvyral.com
  eval: http://homeevaluation.com
  search: http://homesearch.com

socials:
  facebook: http://facebook.com
  linkedin: http://linkedin.com
  gplus: http://plus.google.com
  youtube: http://youtube.com
  twitter: http://twitter.com
  yelp: http://yelp.com
  zillow: http://zillow.com
  trulia: http://trulia.company

podcast: http://itunes.com



# Navigation
navigation:
 - {title: Our Listings, url: /projects.html}
 - {title: Contact, url: /contact.html}
