source 'https://rubygems.org'
gem 'github-pages'
gem 'jekyll-paginate'
gem 'wdm'
gem 'public_suffix', '1.5.1'
gem 'breakpoint'
gem 'octopress-autoprefixer'
gem 'guard'
gem 'guard-jekyll-plus'
gem 'guard-livereload'
