

#Clients
client:
  name: Joe Somebody
  company: Castle Greyskull
  address: '123 Fake St. Eternia, NE'
  phone: 1-234-567-8910
  email: Someone@email.com
  url: getvyral.com
  eval: 'http://homeevaluation.com'
  search: 'http://homesearch.com'

#Navigation
navigation:
  - title: Our Listings
    url: /projects.html
  - title: Contact
    url: /contact.html

#Socials
socials:
  facebook: 'http://facebook.com'
  linkedin: 'http://linkedin.com'
  gplus: 'http://plus.google.com'
  youtube: 'http://youtube.com'
  twitter: 'http://twitter.com'
  yelp: 'http://yelp.com'
  zillow: 'http://zillow.com'
  trulia: 'http://trulia.company'
podcast: 'http://itunes.com'

hero_image_path: /img/Chicago_downtown.jpg